apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: NodePort
  selector:
    tier: backend
    layer: mongo
  ports:
    - protocol: TCP
      port: 27017
      nodePort: 30037
      targetPort: 27017