FROM php:7.4-cli

# Set working directory
WORKDIR /var/www/html

# Install dependencies
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libzip-dev \
    zip unzip \
    cron vim \
    htop \
    iputils-ping \
    libssl-dev #this for mongodb

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
# Install extensions
#dung de su dung exif_imagetype convert png to jpg
RUN docker-php-ext-install exif
RUN docker-php-ext-install pdo_mysql zip pdo
# exif for image type
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install gd

# Cài đặt extension MongoDB
RUN pecl install mongodb \
    && docker-php-ext-enable mongodb

#socket for rabitMQ
RUN docker-php-ext-install sockets
